POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjQ5ZjFiNGI5ZWNjMDMzOGU3MWNjMyIsImlhdCI6MTYyMjYyNzI3OH0.gMZinQ8YYKV4XoOUhg0zPbCUW_m8BM2sINXfak68afs

{
    "title": ""
}

###
// Invalid signature
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjQ5ZjFiNGI5ZWNjMDMzOGU3MWNjMyIsImlhdCI6MTYyMjYyNzI3OH0.gMZinQ8YYKV4XoOUhg0zPbCUW_m8BM2sINXfak68s

{
    "title": ""
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjQ5ZjFiNGI5ZWNjMDMzOGU3MWNjMyIsImlhdCI6MTYyMjYyNzI3OH0.gMZinQ8YYKV4XoOUhg0zPbCUW_m8BM2sINXfak68afs

{
    "title": "yet another insignificant programming notes",
    "author": "Chua Hock Chuan",
    "url": "https://www3.ntu.edu.sg/home/ehchua/programming/index.html",
    "likes": 5
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjQ5ZjFiNGI5ZWNjMDMzOGU3MWNjMyIsImlhdCI6MTYyMjYyNzI3OH0.gMZinQ8YYKV4XoOUhg0zPbCUW_m8BM2sINXfak68afs

{
    "title": "我的博客",
    "author": "司馬遷",
    "url": "https://www.baidu.com",
    "likes": 5
}